#!/bin/bash
# B. Yin, 2020-02-28

# for cubic system

main(){

    srcdir=`pwd`/emto_full_relax
    workdir1=`pwd`/emto_Cij_orth
    workdir2=`pwd`/emto_Cij_mono

    workdir=emto_dir
    

    #--------------------
    jb=`grep -n 'LAT'   $srcdir/IN.BMDL | head -1 | cut -d ":" -f1`
    jk=`grep -n 'LAT'   $srcdir/IN.KSTR | head -1 | cut -d ":" -f1`
    
    jdm=`grep -n 'DMAX' $srcdir/IN.KSTR | head -1 | cut -d ":" -f1`
    jbz=`grep -n 'IBZ'  $srcdir/IN.KGRN | head -1 | cut -d ":" -f1`


    echo $jb  $jk  $jdm  $jbz


    #--------------------
    j1=`grep -n 'A........='  $srcdir/IN.BMDL | head -1 | cut -d ":" -f1`
    echo $j1  


    #--------------------
    js=`grep -n 'debug' $srcdir/sub.emto | head -1 | cut -d ":" -f1`
    echo $js


    #--------------------
    sub_create_dir  $workdir1  sub_apply_orth
    sub_create_dir  $workdir2  sub_apply_mono
}



sub_create_dir(){

    local mydir=$1
    local mycmd=$2
    echo $mydir  $mycmd

    rm -rI $mydir   
    mkdir  $mydir
    cd     $mydir

    mkdir $workdir
    cd    $workdir


    #--------------------
    for x in $(seq 0.000 0.002 0.010);  do

        dirn=`printf "%.3f" "$x"`
        echo "==>" $dirn
        mkdir $dirn
        cd $dirn
    
        cp $srcdir/IN.*   ./
        cp $srcdir/sub.*  ./
    
        $mycmd
    
        abc=`printf "A........=%10.8f B.......=%10.8f C.......=%10.8f"   "1.0" "$bb" "$cc"`
        echo $abc
        sed $j1's/.*/'"$abc"'/' ./IN.BMDL > ./temp
        mv temp IN.BMDL
    

        unset str1
        str1=`printf "NQ3...=  1 LAT...=%2d IPRIM.= 1 NQR2..= 0"  "$LAT"`
        sed $jb's/.*/'"$str1"'/' IN.BMDL > temp
        mv temp IN.BMDL

        unset str1
        str1=`printf "NQ3...=  1 LAT...=%2d IPRIM.= 1 NGHBP.=13 NQR2..= 0"  "$LAT"`
        sed $jk's/.*/'"$str1"'/' IN.KSTR > temp
        mv temp IN.KSTR

        unset str1
        str1=`printf "(K*W)^2..=  0.000000 DMAX....=    %6.4f RWATS...=      0.10"    "$DMAX"`
        sed $jdm's/.*/'"$str1"'/' IN.KSTR > temp
        mv temp IN.KSTR
        
        unset str1
        str1=`printf "KMSH...= G IBZ..= %2d NKX..= 29 NKY..= 29 NKZ..= %2d FBZ..=  N"  "$LAT"  "$NKZ" `
        sed $jbz's/.*/'"$str1"'/' IN.KGRN > temp
        mv temp IN.KGRN

    
        #-----------------------
        sed $js's/.*/###SBATCH --partition debug/' sub.emto > temp
        mv temp sub.emto
    
        yin_emto_univ_cp_lattice
   
 
        #-----------------------
        echo 'submit dir:' `pwd`
        sbatch sub.emto
        cd ..

    done

    cd ..
    cd ..
    pwd
}



sub_apply_orth(){
    bb=`echo "scale=16; (1 - $x) /(1 + $x)" | bc`
    cc=`echo "scale=16; 1 /(1 - $x^2) /(1 + $x)" | bc`

    LAT=11  #fco 
    DMAX=1.7
    NKZ=29
}



sub_apply_mono(){
    bb=`echo "scale=16; (1 - $x) /(1 + $x)" | bc`
    cc=`echo "scale=16; sqrt(2) /(1 - $x^2) /(1 + $x)" | bc`

    LAT=10  #bco
    DMAX=2.4
    NKZ=41
}



main "$@"; exit



