#!/bin/bash
# B. Yin, 2020-02-29


jb=`grep -n 'A........='  ./IN.BMDL | head -1 | cut -d ":" -f1`
jk=`grep -n 'A........='  ./IN.KSTR | head -1 | cut -d ":" -f1`

echo "==> copy lattice from IN.BMDL to IN.KSTR, lines:" $jb $jk

for i in $(seq 0 1)
do
    jb2=$(( $jb + $i ))
    jk2=$(( $jk + $i ))

    unset myline
    myline=`sed -n "$jb2,$jb2 p" ./IN.BMDL`
    sed $jk2's/.*/'"$myline"'/' ./IN.KSTR > ./temp
    mv temp IN.KSTR
done



