#!/bin/bash
# B. Yin, 2019-03-01
# for EMTO


if [ -z "$1" ]; then      # empty $1 is true 
    iex=TOT-PBE

else
    case "$1" in
        -p07) iex=TOT-P07 
              ;;
    
        -lda) iex=TOT-LDA
              ;;

           *) iex=TOT-PBE
              ;;   
    esac
fi

echo "==> grep total energy" $iex







workdir=`pwd`/emto_dir

p_data=`pwd`/emto_post_data
p_time=`pwd`/emto_post_time
p_diff=`pwd`/emto_post_diff
p_param=`pwd`/emto_post_param




echo 'i1  ' $iex '(Ry)   SWS (bohr) ' >   $p_data
echo 'i1   FINISH? ' >   $p_time
echo 'DIFF'          >   $p_diff
echo 'Param'         >   $p_param



dir1=`ls -d -- $workdir/*/  |   head -1`
refdir=$dir1


declare -a arr=(
"IN.BMDL"
"IN.KSTR"
"IN.SHAPE"
"IN.KGRN"
"IN.KFCD"
"sub.emto"
)



ut=0
uf=0



#===================
# loop
#===================

for i1 in `ls $workdir`
do

echo -e "\n==>" $i1
resdir=$workdir/$i1



#-------------------


str1=`grep $iex $resdir/*.kfcd `
echo 'str1=' $str1

Etot=`echo $str1 | awk '{printf "%16.8f", $2}'`
echo 'Etot=' $Etot

SWS=`echo $str1 | awk '{printf "%16.8f", $7}'`
echo 'SWS=' $SWS


echo -e $i1"\t"$Etot"\t"$SWS >> $p_data



#-------------------




slurm=`ls -t $resdir/slurm* | head -1`
k1=`grep -A1 "elapsed time" $slurm | tail -1` 

k2=`grep 'Finished at' $resdir/*.kfcd`

echo -e $i1"\t"$k1"\t"$k2 >> $p_time



#-------------------




ut=$[$ut+1]

if [ "$k1" = "" ]
then
  uf=$[$uf+1]
fi




echo -e "\n==================\n "$i1"\n==================\n " >> $p_diff



for j1 in "${arr[@]}"
do
   echo -e "\n$j1:\n"       >> $p_diff ; 
   diff $refdir/$j1   $resdir/$j1   >> $p_diff
done






echo -e "\n==================\n "$i1"\n==================\n " >> $p_param

grep IEX  $resdir/*.kgrn | head -1  >> $p_param
echo -e " "  >> $p_param

grep AFM  $resdir/*.kgrn | head -1  >> $p_param
echo -e " "  >> $p_param

grep NOS  $resdir/*.kgrn >> $p_param
echo -e " "  >> $p_param




grep "Total FCD"   $resdir/*.kfcd >> $p_param
echo -e " "  >> $p_param

grep Mag   $resdir/*.kfcd >> $p_param 
echo -e " "  >> $p_param

grep CONC  $resdir/*.kfcd >> $p_param





done
#===================


echo -e "\n----------------------------------"
echo "|  total number of jobs: " $ut
echo "|      un-finished jobs: " $uf
echo -e "----------------------------------\n"

cat $p_time
echo -e " "

ls -lshG $workdir/*/slurm-*
echo -e " "


